'use strict';
const FluxConstant = require('flux-constant');


module.exports = FluxConstant.set([
    'GET_ACCOUNT_SETTINGS',
    'GET_ACCOUNT_SETTINGS_RESPONSE',
    'SAVE_ACCOUNT_SETTINGS',
    'SAVE_ACCOUNT_SETTINGS_RESPONSE',
    'HIDE_ACCOUNT_SAVE_SUCCESS',
    'GET_USER_SETTINGS',
    'GET_USER_SETTINGS_RESPONSE',
    'SAVE_USER_SETTINGS',
    'SAVE_USER_SETTINGS_RESPONSE',
    'HIDE_USER_SAVE_SUCCESS',
    'SAVE_PASSWORD_SETTINGS',
    'SAVE_PASSWORD_SETTINGS_RESPONSE',
    'HIDE_PASSWORD_SAVE_SUCCESS'
]);
